### ISSUE TITLE
Couldnt find a column: id  defaulting to noedit

### ISSUE THREAD

**Issue by zeixit** [AccelerationNet/wp-db-table-editor#10]
Strangely enough, this nice WP plugin worked fine - until today.

I see a JS error:
db-table-editor.js:371 Couldnt find a column: id  defaulting to noedit

I clearly have a column "id", and I guess my PHP options are set all correct:
  add_db_table_editor(array(
    'title'=>'Kalkulator Grundpreise aussen',
    'id_column' => 'id',
    'table'=>'kalk_grundpreise_aussen',
    'noedit_columns' => 'code, str',
    'sql'=>'SELECT code, str, baseprice FROM kalk_grundpreise_aussen'
  ));

Running the latest WP core + also just updated your plugin, but the error persists. (it worked normally 1-2 months ago).

Any hints?

**Comment by bobbysmith007** [comment]
The error message is being completely honest.  If you look at the sql you are running there is no ID column in the result set: `SELECT code, str, baseprice FROM kalk_grundpreise_aussen`,  The table might have an id, but if its not in the results, we dont have enough information to write to the database.

**Comment by bobbysmith007** [comment]
ps: `SELECT code, str, baseprice, id FROM kalk_grundpreise_aussen` should fix it
