### ISSUE TITLE
WP 4.8 not working

### ISSUE THREAD

**Issue by pakman198** [AccelerationNet/wp-db-table-editor#27]
Hi, I can't see the plugin on wordpress 4.8 version

I would really appreciate it if you could submit a fix.

Thanks in advance

**Comment by bobbysmith007** [comment]
The plugin is working fine for me on many instances of 4.8.

Are you sure you have correctly configured the plugin per the README?  There is no visible interface until you have added one in your theme's functions file.  Cheers

https://github.com/AccelerationNet/wp-db-table-editor/blob/master/README.md#adding-an-interface

**Comment by pakman198** [comment]
Hi, this is the first time i use the plugin, someone set it up on the website before me and i made some changes and created a child theme, so the reference to the plugin was lost and there was no menu option visible.
Thanks !

**Comment by bobbysmith007** [comment]
Ahh no problem my friend.  Hope you can accomplish what you need :+1:
