### ISSUE TITLE
"New" button attempts editing uneditable cell

### ISSUE THREAD

**Issue by Patrick-1994-** [AccelerationNet/wp-db-table-editor#31]
I clicked "New" and nothing happened (no error, no console log).

The "New button" code says `onclick="DBTableEditor.gotoNewRow();"`
which executes
```
DBTableEditor.gotoNewRow = function () {
  DBTableEditor.grid.gotoCell(DBTableEditor.grid.getDataLength(), 0, true);
};
```
so I substituted it with 1 and it worked fine. It does nothing if cell 1 is the ID, though (`SELECT *`), then I had to use `2`.

SQL-Dump of the table: https://www.dropbox.com/s/sz9z13i8dj03c4r/friedhoefe.sql?dl=1

PHP-Code:
(`require_once` ed in `themes/some_name-child/functions.php`)

```php
<?php
if(function_exists("add_db_table_editor")) {
	$table_name = "friedhoefe";
	$column_names = array(
		"adresse" => "Adresse"
	);
	add_db_table_editor(array(
		"id" => "table_friedhoefe",
		"title" => "Friedhoefe verwalten",
		"table" => $table_name,
		"sql" => "SELECT firma, adresse, plz, ort, versandkostenklasse, id FROM $table_name",
		### columnFilters => $column_filters,
		"editcap"=>"edit_others_posts",
		"autoHeight" => true,
		"columnNameMap" => $column_names,
		#"noedit_columns" => array("id"),
		#"hide_columns" => array("id")
	));
}
```

**Comment by bobbysmith007** [comment]
All the new button does is select the first cell if the last row.  If the first cell isn't editable then it doesn't pull up an edit box.  I guess we could find the first index which is editable and use that instead as that will be different for every result set.  I'm not sure if that's necessary, but is perhaps nicer UI

 My intention, was to simplify navigation, which it does, as you can then use the arrows to navigate left and right filling in data.

**Comment by Patrick-1994-** [comment]
I did not expect that you knew about this bug and did not think fixing was important, I thought it was some weird edge case, well...

The problem is that since is the only / only easy to find table manager, technically unsavvy customers will use it, too. ^^ Tbh, when the New button "did not work", I assumed I could not create new entries and looked into adapting my self-written mini-plugins, only to give yours a second try and noticing the actual point of the button ("how is this "gotoNewCell" thing supposed create a new cell? Huh, it isn't. :D ").

**Comment by bobbysmith007** [comment]
> I did not expect that you knew about this bug and did not think fixing was important, I thought it was some weird edge case, well...

Well its not really a bug, but I did go ahead and enhance this to make it a little clearer what is happening.  

I am now labeling the "new-row" now as well as selecting the first editable column. 

68d5b788206b42d1b33a1631e2ecbcba1651e14c

Cheers,
Russ
