### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by raphaguasta** [AccelerationNet/wp-db-table-editor#35]
Hello guys!

I need to use pagination with wp-db-table-editor, because my table is too big.

I didn't find any documentation about it, is it possible to do that?

Thanks!

**Comment by bobbysmith007** [comment]
That was just added recently (and so may not be quite as stable as other code paths).  You should be able to set "page_size" in the add_db_table_editor and it should take care of the rest of it.  

I had managed to get by without it for a long time, but recently had to make 100,000 rows accessible so I added it in.  

Please feel free to add more bug reports / comments. Thank you
