### ISSUE TITLE
Table Editor Menu Not Showing

### ISSUE THREAD

**Issue by tmm72** [AccelerationNet/wp-db-table-editor#36]
Wordpress 5.2.1
DB-Table-Editor 1.7.3

Wordpress was updated and the DB-Table-Editor isn't showing in the left menu anymore.
Have reinstalled etc with no change.

Let me know if you need more information.

**Comment by bobbysmith007** [comment]
Its working for me on those versions, so it must be something about your local configuration.  

Other than verifying its activated, I would try turning on debugging (https://wordpress.org/support/article/debugging-in-wordpress/) and seeing if you can get an error message of some variety.  Check your server logs if you have access to them.

If you want to post the configuration that you have been using that is failing I am happy to look at it  / try to help you find the issue

**Comment by tmm72** [comment]
Oh I did a rookie mistake the functions file was updated and removed the db table editor was removed.
Thanks for the reply

**Comment by bobbysmith007** [comment]
No problem and glad you figured it out :) - Thanks for helping make the plugin eco system stronger by communicating.  Cheers
