### ISSUE TITLE
Delete option not available

### ISSUE THREAD

**Issue by kantha05** [AccelerationNet/wp-db-table-editor#5]
Hi there,

I'm new to this plugin. First of all, I would like to thank you for this wonderful plugin. I'm using it for the past few weeks. On the plugin description I see that we can delete the row of the table using the delete button next to the row but in my case, I'm not seeing the delete button there. Please help me on how to get it.

FYI, I have added these codes in my functions.php file

function dbTableEditorScripts(){
  wp_register_script('employee-table-extensions-js',
    get_stylesheet_directory_uri().'/employee-table.js',
    array('db-table-editor-js'));
}
  add_action('db-table-editor_enqueue_scripts', 'dbTableEditorScripts');

function pa_admin_area_favicon() {
    $favicon_url = get_option('ws_favicon');
    echo '<link rel="shortcut icon" href="' . $favicon_url . '" />';
}
add_action('admin_head', 'pa_admin_area_favicon'); if(function_exists('add_db_table_editor')){ add_db_table_editor(array( 'title'=>'[page title]', 'table'=>'[table-name]', 'sql'=>'SELECT \* FROM [table-name] ORDER BY sub_id DESC' ));}

Please let me know if I have missed anything.

Thanks in advance.

-Kantha

**Comment by bobbysmith007** [comment]
Sorry I apparently missed you updates to this (months and months ago).  This plugin is mostly intended to be used from admin screens.  Recently a patch that makes it work on public facing pages was added to allow this to work.

All configuration code needs to happen  BEFORE the `admin_menu` action. The best place to put the configuration code is in the theme's "functions.php" file or in a plugins php file.

As noted however, this plugin was written by an experienced developer for experienced developers.  I hope you were able to make it work, but if not there are more streamlined options available for crud that provides admin screens.
