### ISSUE TITLE
How to used the following add_db_table_editor arguments

### ISSUE THREAD

**Issue by francisalfanta** [AccelerationNet/wp-db-table-editor#7]
Thank you for this great plugin. It totally saves my time re-creating much of datatable functionality.  
I am trying to used the other argument that you mention in your README such as  ‘dataFn’,  ‘jsFile’, ‘cap’, ‘editcap’, ‘noedit’, ‘columnFilters’, ‘columnNameMap’, ‘noedit_columns’, ‘hide_column’,  ‘insert_cb’, ‘update_cb’, ‘delete_cb’, ‘auto’_date’  and ‘autoHeight’. But I can’t figure out how.

add_db_table_editor(array( 'title'=>'Bank Lists', 
                               'table'=>'bank_lists', 
                               'sql'=>'SELECT * FROM foo_lists ORDER BY name DESC',
                               'auto_date',
                               'columnNameMap' =>'ID, Star, Name, City, Community, Subcommunity, Street, Bldg  Name, Phone no, Fax no, Email, Contact Person, Mobile No, Status, Remarks, Created, Updated'
                              )

Can somebody provide an example how to used each argument?

**Comment by bobbysmith007** [comment]
Thank you for your feedback.

I will make an attempt at improving the documentation.  Alternatively, if you figure it out and wish to provide the documentation that you need, for the rest of the community, I will be sure to merge any patches.

**Comment by bobbysmith007** [comment]
Please have a look at the new examples file.  It does not cover all the options, but does provide examples for quite a few more.

https://github.com/AccelerationNet/wp-db-table-editor/blob/master/examples/cf7dbsubmit_integration.php
